export const clientsData = [
  { id: 1, name: "Axis Bank", logo: "https://exato.ai/Axis-Bank.jpeg" },
  { id: 2, name: "Bank of India", logo: "https://exato.ai/2-Bank-of-India-p-500.jpeg" },
  { id: 3, name: "Citi Bank", logo: "https://exato.ai/4-Citi-Bank-p-500.jpeg" },
  { id: 4, name: "DSP BlackRock", logo: "https://exato.ai/5-DSP-BlackRock-Mutual-Fund-p-500.jpeg" },
  { id: 5, name: "Edelweiss", logo: "https://exato.ai/6-Edelweiss-p-500.jpeg" },
  { id: 6, name: "ICICI Securities", logo: "https://exato.ai/7-ICICI-Securities-p-500 (1).jpeg" },
  { id: 7, name: "IDFC Bank", logo: "https://exato.ai/8-IDFC-Bank-p-500.jpeg" },
  { id: 8, name: "JM Financial", logo: "https://exato.ai/9-JM-Financial-p-500.jpeg" },
  { id: 9, name: "Kotak Mahindra Bank", logo: "https://exato.ai/10-Kotak-Mahindra-Bank-p-500.jpeg" },
  { id: 10, name: "Mirae Asset", logo: "https://exato.ai/11-Mirae-Asset-p-500.jpeg" },
  { id: 11, name: "OCBC Bank", logo: "https://exato.ai/12-OCBC-Bank-p-500.jpeg" },
  { id: 12, name: "Reliance Capital", logo: "https://exato.ai/13-Reliance-Capital-p-500.jpeg" },
  { id: 13, name: "SBI Mutual Fund", logo: "https://exato.ai/14-SBI-Mutual-Fund-p-500.jpeg" },
  { id: 14, name: "SBM Bank", logo: "https://exato.ai/15-SBM-Bank-p-500.jpeg" },
  { id: 15, name: "TATA Capital", logo: "https://exato.ai/16-TATA-Capital-p-500.jpeg" },
];